# -*- coding: utf-8 -*-
"""Fakultät

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nd7C3GSGdkUoYLs7-t4GEpRtPrCEADe7
"""

n = 5
fak = 1

while n > 0 :
  fak = fak * n
  n = n - 1

print(fak)