# -*- coding: utf-8 -*-
"""Kino

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16hJDsXIRD3ODITpGAEBcLresWpyrJ0rN
"""

alter = 16
in_begleitung = False

if in_begleitung :
  print("Du darfst Filme ab 0, 6, 12, 16 und 18 Jahren schauen.")
elif alter >= 18 :
  print("Du darfst Filme ab 0, 6, 12, 16 und 18 Jahren schauen.")
elif alter >= 16 :
  print("Du darfst Filme ab 0, 6 12 und 16 Jahren schauen.")
elif alter >= 12 :
  print("Du darfst Filme ab 0, 6 und 12 Jahren schauen.")
elif alter >= 6 :
  print("Du darfst Filme ab 0, 6 Jahren schauen.")
else :
  print("Du darfst Filme ab 0 Jahren schauen.")