# -*- coding: utf-8 -*-
"""ListenAufgaben.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10LwyqPj7gn0-l51eLOBc1Xl7Bw0jp3Uw
"""

liste = [] # Liste für Zahlen die durch 3 teilbar sind
zaehler = 0

while zaehler <= 100 :
  if zaehler % 3 == 0 : # Zaehler ist durch 3 teilbar
    liste.append(zaehler)
  zaehler = zaehler + 1

print(liste)

l = [0,5,2,42,8,30] # Liste l aus der Aufgabenstellung
max = l[0] # initial ist max einfach das erste Element

for i in l :
  if i >= max : # Wenn i groeßer ist als max wird max auf i gesetzt
    max = i

print(max)

l = [0,5,2,42,8,30] # Liste mit geraden und ungeraden Zahlen
liste_gerade = [] # Liste mit allen geraden Zahlen aus der Liste l

for i in l :
  if i % 2 == 0 : # Wenn i gerade ist wird es der liste_gerade hinzugefuegt
    liste_gerade.append(i)

print(liste_gerade)